# -*- coding: utf-8 -*-
"""DE_Practical-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1garjbS4CV92PO_yw4WaR0AGidDAAAWjX

# Practical-6
"""

!pip install apache-airflow -q

import os
import subprocess

os.environ["AIRFLOW_HOME"] = "/content/airflow"
os.environ["AIRFLOW__CORE__DAGS_FOLDER"] = "/content/airflow/dags"

os.makedirs("/content/airflow/dags", exist_ok=True)

# Create extraction script
with open("/content/airflow/data_extraction.py", "w") as f:
    f.write("""
print("Starting data extraction...")
print("Extracting data from source...")
print("Data extraction completed successfully.")
""")

# Create Airflow DAG
with open("/content/airflow/dags/data_pipeline_dag.py", "w") as f:
    f.write("""
from datetime import datetime, timedelta

from airflow.sdk import DAG
from airflow.providers.standard.operators.bash import BashOperator
from airflow.providers.standard.operators.empty import EmptyOperator

default_args = {
    "owner": "data_engineering_lab",
    "depends_on_past": False,
    "start_date": datetime(2026, 1, 1),
    "retries": 1,
    "retry_delay": timedelta(minutes=5),
}

with DAG(
    dag_id="university_etl_orchestration",
    default_args=default_args,
    description="ETL pipeline orchestration",
    schedule="@daily",
    catchup=False,
) as dag:

    start_pipeline = EmptyOperator(
        task_id="start_pipeline"
    )

    execute_extraction = BashOperator(
        task_id="run_extraction_script",
        bash_command="python /content/airflow/data_extraction.py"
    )

    pipeline_complete = BashOperator(
        task_id="log_pipeline_success",
        bash_command='echo "ETL Execution completed successfully"'
    )

    start_pipeline >> execute_extraction >> pipeline_complete
""")

print("DAG created successfully.")
print("DAG Name: university_etl_orchestration")
print("Schedule: Daily")
print()

# Initialize Airflow database
subprocess.run(
    ["airflow", "db", "migrate"],
    env=os.environ
)

print("\nRunning DAG tasks...\n")

# Run complete DAG
result = subprocess.run(
    [
        "airflow",
        "dags",
        "test",
        "university_etl_orchestration",
        "2026-08-20"
    ],
    env=os.environ,
    capture_output=True,
    text=True
)

print(result.stdout)

if result.stderr:
    print(result.stderr)

print("\nETL Pipeline Practical Completed!")

