# -*- coding: utf-8 -*-
"""DE_Practical-8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PGlodp0nkQ1xrR6kzqvyb7FlgGhc1guU

# Practical -8
"""

pip show pyspark

from pyspark.sql import SparkSession
from pyspark.sql.functions import avg, sum

spark = SparkSession.builder.appName("Practical8").getOrCreate()

# Create sample sales data
data = [
    (1, "Laptop", "Electronics", 50000),
    (2, "Phone", "Electronics", 30000),
    (3, "Chair", "Furniture", 5000),
    (4, "Table", "Furniture", 8000),
    (5, "Laptop", "Electronics", 50000),
    (5, "Laptop", "Electronics", 50000)
]

columns = ["ID", "Product", "Category", "Sales"]

df = spark.createDataFrame(data, columns)

print("\n--- 1. Schema ---")
df.printSchema()

print("\n--- 2. Filtering ---")
df.filter(df.Sales > 10000).show()

print("\n--- 3. Grouping and Aggregation ---")
df.groupBy("Category").agg(sum("Sales").alias("Total_Sales")).show()

print("\n--- 4. Remove Duplicate Records ---")
df.dropDuplicates().show()

# Second dataset for join
customer_data = [
    (1, "Amit"),
    (2, "Neha"),
    (3, "Rahul"),
    (4, "Priya"),
    (5, "Ankit")
]

customers = spark.createDataFrame(customer_data, ["ID", "Customer"])

print("\n--- 5. Join ---")
df.join(customers, "ID", "inner").show()

print("\n--- 6. Average Sales by Product Category ---")
df.groupBy("Category").agg(
    avg("Sales").alias("Average_Sales")
).show()

spark.stop()

