# -*- coding: utf-8 -*-
"""DE_Practical-9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xl7rUCktdikB8alVxx68HJZZBeu0hqac

# Practical 9
"""

import pandas as pd
import sqlite3

print("========== PRACTICAL 9: END-TO-END ETL PIPELINE ==========")

# 1. Historical E-Commerce Data
print("\n--- 1. Historical Data ---")

customers = pd.DataFrame({
    "CustomerID": [1, 2, 3],
    "Name": ["Amit", "Neha", "Rahul"]
})

products = pd.DataFrame({
    "ProductID": [101, 102, 103],
    "Product": ["Laptop", "Phone", "Headphones"],
    "Price": [50000, 30000, 2000]
})

orders = pd.DataFrame({
    "OrderID": [1, 2, 3],
    "CustomerID": [1, 2, 3],
    "ProductID": [101, 102, 103],
    "Quantity": [1, 2, 3]
})

payments = pd.DataFrame({
    "PaymentID": [1, 2, 3],
    "OrderID": [1, 2, 3],
    "Amount": [50000, 60000, 6000]
})

print("Customers:")
print(customers)
print("\nProducts:")
print(products)
print("\nOrders:")
print(orders)
print("\nPayments:")
print(payments)

# 2. Data Cleaning and Transformation
print("\n--- 2. Data Cleaning and Transformation ---")

customers.drop_duplicates(inplace=True)
orders.dropna(inplace=True)

orders["Total"] = orders["Quantity"] * orders["ProductID"].map(
    products.set_index("ProductID")["Price"]
)

print(orders)

# 3. Newly Arriving Data
print("\n--- 3. Newly Arriving Data ---")

new_orders = pd.DataFrame({
    "OrderID": [4],
    "CustomerID": [1],
    "ProductID": [102],
    "Quantity": [1]
})

new_orders["Total"] = new_orders["Quantity"] * new_orders["ProductID"].map(
    products.set_index("ProductID")["Price"]
)

print(new_orders)

# 4. Historical + New Data
print("\n--- 4. Combined Data ---")

orders = pd.concat([orders, new_orders], ignore_index=True)

print(orders)

# 5. Load into SQL Database
print("\n--- 5. SQL Database Loading ---")

conn = sqlite3.connect("ecommerce.db")

customers.to_sql("customers", conn, if_exists="replace", index=False)
products.to_sql("products", conn, if_exists="replace", index=False)
orders.to_sql("orders", conn, if_exists="replace", index=False)
payments.to_sql("payments", conn, if_exists="replace", index=False)

print("Customers, Products, Orders and Payments loaded successfully.")

# 6. Generate Report
print("\n--- 6. Final E-Commerce Report ---")

report = pd.read_sql("""
SELECT c.Name, p.Product, o.Quantity, o.Total
FROM orders o
JOIN customers c ON o.CustomerID = c.CustomerID
JOIN products p ON o.ProductID = p.ProductID
""", conn)

print(report)

conn.close()

print("\n========== ETL PIPELINE COMPLETED ==========")

